# Generated by Django 3.2.5 on 2021-08-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(choices=[('physics', 'Physics'), ('math', 'Mathematics'), ('cs', 'Informatics'), ('electronics', 'Electronics')], max_length=25)),
                ('coursetype', models.CharField(choices=[('lecture', 'Lecture'), ('seminar', 'Seminar'), ('practical', 'Practical')], max_length=25)),
                ('credits', models.PositiveIntegerField(null=True)),
                ('grade', models.FloatField(null=True)),
                ('gradescale', models.CharField(choices=[('german', 'Best: 1.0; Worst: 5.0'), ('100scale', 'Best: 100; Worst: 0'), ('50scale', 'Best: 50; Worst: 0')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('externallinks', models.TextField(blank=True)),
                ('courselevel', models.CharField(choices=[('school', 'High School'), ('bachelors', 'Bachelors'), ('masters', 'Masters')], default='Masters', max_length=25)),
            ],
        ),
    ]
