# Generated by Django 3.2.5 on 2021-08-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courselevel',
            field=models.CharField(choices=[('others', 'Others'), ('bachelors', 'Bachelors'), ('masters', 'Masters')], default='masters', max_length=25),
        ),
    ]
