# Generated by Django 3.2.5 on 2021-08-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_courselevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='gradealphabet',
            field=models.CharField(choices=[('a', 'A'), ('a-', 'A-'), ('b+', 'B+'), ('b', 'B'), ('c', 'C')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='courselevel',
            field=models.CharField(choices=[('others', 'Others'), ('bachelors', 'Bachelors'), ('masters', 'Masters')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='gradescale',
            field=models.CharField(choices=[('german', 'Best: 1.0; Worst: 5.0'), ('100scale', 'Best: 100; Worst: 0'), ('50scale', 'Best: 50; Worst: 0')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(choices=[('physics', 'Physics'), ('math', 'Mathematics'), ('cs', 'Computer Science'), ('electronics', 'Electronics'), ('stats', 'Statistics'), ('philosophy', 'Philosophy'), ('arts', 'Arts')], max_length=25),
        ),
    ]
